### PR TITLE
feat: seed client

### PR DESCRIPTION
**Pull request by renzholy**
https://github.com/starcoinorg/starcoin-explorer/issues/79

### CODE REVIEW

**Comment by tarvos21** [comment]
> #79

What's `REACT_APP_SEED_API_URL`?

**Comment by renzholy** [comment]
> What's `REACT_APP_SEED_API_URL`?

like https://main-seed.starcoin.org

**Comment by tarvos21** [comment]
> > What's `REACT_APP_SEED_API_URL`?
> 
> like https://main-seed.starcoin.org

so how do you set the ENV for different networks?

**Comment by renzholy** [comment]
@tarvos21 fixed

**Review by tarvos21 — APPROVED** [review]

**Pull request merged**
